### ISSUE TITLE
图片名传空值,报警告CUICatalog: Invalid asset name supplied: (null)

### ISSUE THREAD

**Issue by XYXiaoYuan** [chenfanfang/FFDropDownMenu#1]
解决方式是判断下有没有图片名字符串,如果没有图片,就不设置
- (void)setMenuModel:(id)menuModel {
  _menuModel = menuModel;
  
  FFDropDownMenuModel *realMenuModel = (FFDropDownMenuModel *)menuModel;
  self.customTitleLabel.text = realMenuModel.menuItemTitle;
  //给imageView赋值
  // 先判断是否有图片名
  if (realMenuModel.menuItemIconName.length) {
      self.customImageView.image = [UIImage imageNamed:realMenuModel.menuItemIconName];
  }
  }

**Comment by chenfanfang** [comment]
好的，谢谢您的建议，过些天我处理下

**Comment by chenfanfang** [comment]
已经处理完毕
