### ISSUE TITLE
xcode8，swift3下问题，样式没了

### ISSUE THREAD

**Issue by yujianfeikong** [chenfanfang/FFDropDownMenu#3]
用pod引入后，显示效果成这样了。没升级之前是没问题的。这个怎么处理？
![wenti](https://cloud.githubusercontent.com/assets/22102597/20554063/524fe144-b194-11e6-849f-eb8ac83b8c28.png)

![daima](https://cloud.githubusercontent.com/assets/22102597/20554089/791300b8-b194-11e6-927f-21a2cee478ec.png)

**Comment by yujianfeikong** [comment]
上面是用的最新版本，还原成1.3.5就有背景了
![wenti2](https://cloud.githubusercontent.com/assets/22102597/20554702/94553554-b198-11e6-9a1c-5341e1209af7.png)

**Comment by chenfanfang** [comment]
谢谢你的反馈，上一版本的问题已经修复，并且增加了部分属性，可对默认菜单样式的部分属性进行调整。比如:比如图片大小的设置、文字颜色、边距等等。
